config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  root 'users#index'

  get "/secret", to: "secrets#show", as: "t_secret"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  before_save { email.downcase! }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  
  def show
  
    @current_user = User.find_by(id: session[:user_id])

    if !!(@current_user && logged_in?)
    else
      redirect_to root_url
      flash.now[:danger] = "You are not connected and can't see the answer !" # Not quite right!

    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
  		log_in user
  		redirect_to user
  	else 
  		flash.now[:danger] = "Invalid email / password combination "
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def index

	@users = User.all

  end

  def new

  	@user = User.new

  end

  def create
	@user = User.new(user_params)
	if @user.save 
		log_in @user
    flash[:success] = "Welcome to my website"
    redirect_to @user
	else 
		render 'new'
	end
  end

  def show

  	@user = User.find(params[:id])

  end

  def edit

  	@user = User.find(params[:id])

  end

  def update

  	@user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
    render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
	
	params.require(:user).permit(:email, :password)
  
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

   # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

    # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Secret Universe", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home / Index", root_path %></li>
        <li><%= link_to "Secret", t_secret_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/secrets/show.html.erb
<h1>Tu as vraiment cru que ce site cachait un secret...</h1>
<p> désolé de te décevoir </p>

app/views/users/edit.html.erb
<h1>Modifier le User</h1>

<%= form_with model: @user, local: true do |form| %>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.label :password %><br>
    <%= form.text_area :password %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>


<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Index des users enregistrés</h1>
<p>Bienvenue sur mon app</p>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      	<td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div><%= link_to"New user",new_user_path %></div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
<p><%= f.label :email %><br>
   <%= f.text_field :email %></p>
 <p><%= f.label :password %><br>
    <%= f.text_field :password %></p>
  <%= f.submit "Create" %>
<% end %>

</br>
<div><%= link_to"Back",root_path %></div>

app/views/users/show.html.erb
<h1>User info</h1>

<p class="show-text">User email</p>
<p><%= @user.email %></p>

<p class="show-text"> Password digest</p>
<p><%= @user.password_digest %></p>


<div><%= link_to"Back",root_path %></div>